### ISSUE TITLE
display danmu 模块benchmark报错 ClassCastException

### ISSUE THREAD

**Issue by LatiosInAltoMare** [hezean/sustc#101]
### Related module

Benchmark

### What happened

跑benchmark的时候（测试display弹幕时）报错ClassCastException，报错地点在BenchmarkService 251行
报错的代码：
`
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.util.Collection (java.lang.Integer and java.util.Collection are in module java.base of loader 'bootstrap')
	at io.sustc.benchmark.BenchmarkService.lambda$danmuDisplay$7(BenchmarkService.java:251) ~[main/:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[na:na] 
`

### What you expected to happen

报错的部分似乎没有涉及api

**Comment by hezean** [comment]
please update your framework

**Comment by LatiosInAltoMare** [comment]
但是我好像更新过了欸 昨天晚上下载的最新的版本 o(TヘTo)

**Comment by LatiosInAltoMare** [comment]
感谢~
