### ISSUE TITLE
benchmark service has a bug

### ISSUE THREAD

**Issue by Mandyyymeng** [hezean/sustc#112]
### Related module

Benchmark

### What happened

does this bug has somthing to do with the benchmark? nextint generates a integer smaller than 0
![Uploading image.png…]()

**Comment by Mandyyymeng** [comment]
2023-12-31 15:16:33.524 ERROR 28292 --- [onPool-worker-8] io.sustc.benchmark.BenchmarkService      : Exception thrown for 881943

java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:322) ~[na:na]
	at io.sustc.benchmark.BenchmarkService.lambda$danmuLike$10(BenchmarkService.java:332) ~[main/:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[na:na]
